services:
  - type: worker
    name: celery-worker
    region: oregon
    runtime: python
    buildCommand: "poetry install"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: redis-backend
          type: redis
          property: connectionString